### ISSUE TITLE
Metrics not being sent to Cloud Watch

### ISSUE THREAD

**Issue by felipe-gdr** [dkublik/m3trics#1]
Hey Dawid, great write up!

I've deployed this example code in AWS and the app is running fine, no errors on the logs and I can hit the `/lucky-numbers` endpoint. However, I can't see any metrics from the `m3trics2` namespace in CloudWatch. I see other metrics, like EC2 and other services I have running, but nothing from the m3trics app. 

Is there any configuration that needs to be done in CloudWatch in order for the new metrics to appear?

Cheers!
Felipe.

**Comment by dkublik** [comment]
Hi Felipe,
It appears that in this article: https://dkublik.github.io/2018/08/26/springboot-metrics-with-micrometer-and-aws-cloudwatch.html
I was pointing to wrong (old) repo - when spring boot was still working with servo. 
The new version of this project using micrometer can be found here: https://github.com/dkublik/micrometer-aws-example
maybe in the meantime sth with the aws client changed.
Hope the new one will work.
Br
__
Dawid

**Comment by felipe-gdr** [comment]
Awesome! It's working great now, thanks @dkublik :-)
